# Generated by Django 6.0.5 on 2026-05-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='daily_target_hours',
            field=models.IntegerField(default=2),
        ),
    ]
